#!/usr/bin/env python3
# EASY-INSTALL-ENTRY-SCRIPT: 'rst2pdf==0.16','console_scripts','rst2pdf'
from __future__ import absolute_import
__requires__ = 'rst2pdf'
import sys
from importlib import metadata

import zot4rst
import xciterst.directives

def run():
    sys.exit(
        metadata.entry_points().select(name='rst2pdf', group='console_scripts').load()
    )
